# docker-compose --project-name web -f docker-nginx/docker-compose.yml down -v
# docker-compose --project-name web -f docker-nginx/docker-compose.yml up -d
version: '3.1'
services:
  app:
    container_name: app
    image: nginx:1.10.3-alpine
    volumes:
      - app-volume:/var/log/nginx
      - ../dist:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    networks:
      - app-external-net
volumes:
  app-volume:
    driver: local
networks:
  app-external-net:
    driver: bridge
